#!/usr/bin/env bash

lua_argparse_version="0.7.0-1"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

luarocks_install "argparse" "$lua_argparse_version"

# Hijacking this to install other deps
luarocks_install "lua-resty-session"
luarocks_install "lua-resty-jwt"
luarocks_install "lua-resty-http"
luarocks_install "lua-resty-openidc"
luarocks_install "luacrypto"


stamp
